In [4]:
import numpy as np
arr=np.arange(0,11)
arr1=[1,2,3,4,5]
print(arr1)
print(arr)

[1, 2, 3, 4, 5]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [2]:
import numpy as np
np.random.seed(42)

In [3]:
def analyze_temperatures(temps):
    temps = np.array(temps)
    avg = temps.mean()
    maximum = temps.max()
    minimum = temps.min()
    hottest_day = temps.argmax() + 1  # 1-indexed day
    above_avg = temps[temps > avg]
    return {
        'average': avg,
        'max': maximum,
        'min': minimum,
        'hottest_day': hottest_day,
        'above_average': above_avg
    }

temperatures = np.array([32.5, 31.8, 30.2, 33.1, 34.5, 29.8, 31.0])
result = analyze_temperatures(temperatures)
for k, v in result.items():
    print(f'{k}: {v}')

average: 31.842857142857145
max: 34.5
min: 29.8
hottest_day: 5
above_average: [32.5 33.1 34.5]


In [4]:
matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

first_row = matrix[0]
last_row = matrix[-1]
first_col = matrix[:, 0]
last_col = matrix[:, -1]
middle_2x2 = matrix[0:2, 1:3]
alternate_elements = matrix[::2, ::2]

print('First row:', first_row)
print('Last row:', last_row)
print('First column:', first_col)
print('Last column:', last_col)
print('Middle 2x2 section:\n', middle_2x2)
print('Every alternate element:\n', alternate_elements)
print('Shape:', matrix.shape)
print('Dimensions:', matrix.ndim)
print('Total elements:', matrix.size)

First row: [1 2 3 4]
Last row: [ 9 10 11 12]
First column: [1 5 9]
Last column: [ 4  8 12]
Middle 2x2 section:
 [[2 3]
 [6 7]]
Every alternate element:
 [[ 1  3]
 [ 9 11]]
Shape: (3, 4)
Dimensions: 2
Total elements: 12


In [6]:
random_numbers = np.random.choice(np.arange(1, 51), size=20, replace=False)
print('Random numbers:', random_numbers)

even_numbers = random_numbers[random_numbers % 2 == 0]
odd_numbers = random_numbers[random_numbers % 2 != 0]

print('Even numbers:', even_numbers)
print('Odd numbers:', odd_numbers)

Random numbers: [14 40 31 46 18 49 27 26 33 20 13  5 38  9  4  7 42 47 48 16]
Even numbers: [14 40 46 18 26 20 38  4 42 48 16]
Odd numbers: [31 49 27 33 13  5  9  7 47]


In [7]:
random_ints = np.random.randint(1, 101, size=30)
print('Generated array:', random_ints)

greater_than_50 = random_ints[random_ints > 50]
between_25_75 = random_ints[(random_ints >= 25) & (random_ints <= 75)]
count_greater_than_50 = (random_ints > 50).sum()
avg_greater_than_50 = greater_than_50.mean() if greater_than_50.size > 0 else 0

print('Values > 50:', greater_than_50)
print('Values between 25 and 75:', between_25_75)
print('Count > 50:', count_greater_than_50)
print('Average of values > 50:', avg_greater_than_50)

Generated array: [ 9 90 53  2 84 92 60 71 44  8 47 35 78 81 36 50  4  2  6 54  4 54 93 63
 18 90 44 34 74 62]
Values > 50: [90 53 84 92 60 71 78 81 54 54 93 63 90 74 62]
Values between 25 and 75: [53 60 71 44 47 35 36 50 54 54 63 44 34 74 62]
Count > 50: 15
Average of values > 50: 73.26666666666667


In [8]:
import numpy as np

# Store only the numerical marks in a NumPy array
marks = np.array([
    [78, 82, 91],   # Student 1
    [65, 74, 80],   # Student 2
    [92, 88, 95],   # Student 3
    [56, 69, 72],   # Student 4
    [84, 90, 87]    # Student 5
])

subjects = ['Mathematics', 'Physics', 'Programming']

# Average marks of each student (row-wise mean)
avg_per_student = marks.mean(axis=1)

# Average marks in each subject (column-wise mean)
avg_per_subject = marks.mean(axis=0)

# Highest and lowest mark in the entire dataset
highest_mark = marks.max()
lowest_mark = marks.min()

# Student with the highest average
best_student_index = avg_per_student.argmax()

# Subject with the highest average
best_subject_index = avg_per_subject.argmax()

# Display results
print("Marks matrix:\n", marks)
print("\nAverage marks of each student:", avg_per_student)
print("Average marks in each subject:", avg_per_subject)
print("\nHighest mark in the dataset:", highest_mark)
print("Lowest mark in the dataset:", lowest_mark)
print(f"\nStudent with the highest average: Student {best_student_index + 1} "
      f"(avg = {avg_per_student[best_student_index]:.2f})")
print(f"Subject with the highest average: {subjects[best_subject_index]} "
      f"(avg = {avg_per_subject[best_subject_index]:.2f})")

Marks matrix:
 [[78 82 91]
 [65 74 80]
 [92 88 95]
 [56 69 72]
 [84 90 87]]

Average marks of each student: [83.66666667 73.         91.66666667 65.66666667 87.        ]
Average marks in each subject: [75.  80.6 85. ]

Highest mark in the dataset: 95
Lowest mark in the dataset: 56

Student with the highest average: Student 3 (avg = 91.67)
Subject with the highest average: Programming (avg = 85.00)


In [9]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

addition = A + B
subtraction = A - B
elementwise_mult = A * B
matrix_mult = A @ B  # or np.dot(A, B)

print('Addition:\n', addition)
print('Subtraction:\n', subtraction)
print('Element-wise multiplication:\n', elementwise_mult)
print('Matrix multiplication:\n', matrix_mult)

Addition:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Subtraction:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
Element-wise multiplication:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
Matrix multiplication:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [10]:
def transform_measurements(data):
    data = np.array(data)
    squared = data ** 2
    sqrt_vals = np.sqrt(data)
    exp_vals = np.exp(data)
    mean_transformed = {
        'mean_of_squares': squared.mean(),
        'mean_of_sqrt': sqrt_vals.mean(),
        'mean_of_exp': exp_vals.mean()
    }
    return squared, sqrt_vals, exp_vals, mean_transformed

measurements = [2, 4, 6, 8, 10, 12]
squared, sqrt_vals, exp_vals, means = transform_measurements(measurements)

print('Squares:', squared)
print('Square roots:', sqrt_vals)
print('Exponentials:', exp_vals)
print('Means of transformed data:', means)

Squares: [  4  16  36  64 100 144]
Square roots: [1.41421356 2.         2.44948974 2.82842712 3.16227766 3.46410162]
Exponentials: [7.38905610e+00 5.45981500e+01 4.03428793e+02 2.98095799e+03
 2.20264658e+04 1.62754791e+05]
Means of transformed data: {'mean_of_squares': np.float64(60.666666666666664), 'mean_of_sqrt': np.float64(2.5530849508680995), 'mean_of_exp': np.float64(31371.271866746192)}


In [11]:
data = np.arange(1, 25)

reshaped_4x6 = data.reshape(4, 6)
reshaped_6x4 = data.reshape(6, 4)
reshaped_2x3x4 = data.reshape(2, 3, 4)

print('4x6 shape:', reshaped_4x6.shape)
print(reshaped_4x6)
print('6x4 shape:', reshaped_6x4.shape)
print(reshaped_6x4)
print('2x3x4 shape:', reshaped_2x3x4.shape)
print(reshaped_2x3x4)

flattened_back = reshaped_4x6.flatten()
print('Flattened back to 1D:', flattened_back)

4x6 shape: (4, 6)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
6x4 shape: (6, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
2x3x4 shape: (2, 3, 4)
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Flattened back to 1D: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [12]:
experiment_1 = np.array([10, 20, 30, 40, 50])
experiment_2 = np.array([15, 25, 35, 45, 55])

# Single 1D array with all measurements
combined_1d = np.concatenate([experiment_1, experiment_2])

# Matrix where experiments are separate rows
combined_rows = np.vstack([experiment_1, experiment_2])

# Matrix where experiments are separate columns
combined_cols = np.column_stack([experiment_1, experiment_2])

print('1D combined:', combined_1d, 'shape:', combined_1d.shape)
print('Row-wise combined:\n', combined_rows, 'shape:', combined_rows.shape)
print('Column-wise combined:\n', combined_cols, 'shape:', combined_cols.shape)

1D combined: [10 20 30 40 50 15 25 35 45 55] shape: (10,)
Row-wise combined:
 [[10 20 30 40 50]
 [15 25 35 45 55]] shape: (2, 5)
Column-wise combined:
 [[10 15]
 [20 25]
 [30 35]
 [40 45]
 [50 55]] shape: (5, 2)


In [13]:
measurements = np.array([10, 12, 15, 200, 13, 11, 14, 250, 12, 15])

invalid_mask = measurements > 100
invalid_measurements = measurements[invalid_mask]
valid_measurements = measurements[~invalid_mask]

mean_valid = valid_measurements.mean()
min_valid = valid_measurements.min()
max_valid = valid_measurements.max()

print('Original array (unchanged):', measurements)
print('Invalid measurements:', invalid_measurements)
print('Valid measurements:', valid_measurements)
print('Mean of valid measurements:', mean_valid)
print('Min of valid measurements:', min_valid)
print('Max of valid measurements:', max_valid)

Original array (unchanged): [ 10  12  15 200  13  11  14 250  12  15]
Invalid measurements: [200 250]
Valid measurements: [10 12 15 13 11 14 12 15]
Mean of valid measurements: 12.75
Min of valid measurements: 10
Max of valid measurements: 15


In [14]:
image = np.array([
    [0, 0, 0, 255, 255],
    [0, 0, 128, 255, 255],
    [0, 128, 128, 128, 255],
    [0, 0, 128, 0, 0],
    [255, 0, 0, 0, 255]
])

min_intensity = image.min()
max_intensity = image.max()
mean_intensity = image.mean()
count_above_100 = (image > 100).sum()
pixels_255 = image[image == 255]
pixels_above_100 = image[image > 100]

print('Min pixel intensity:', min_intensity)
print('Max pixel intensity:', max_intensity)
print('Mean pixel intensity:', mean_intensity)
print('Number of pixels > 100:', count_above_100)
print('Pixels equal to 255:', pixels_255)
print('New array of pixels > 100:', pixels_above_100)

Min pixel intensity: 0
Max pixel intensity: 255
Mean pixel intensity: 97.0
Number of pixels > 100: 12
Pixels equal to 255: [255 255 255 255 255 255 255]
New array of pixels > 100: [255 255 128 255 255 128 128 128 255 128 255 255]


In [16]:
import numpy as np

# Measurements from the two experiments
experiment_A = np.array([12, 15, 14, 18, 20, 17, 16])
experiment_B = np.array([10, 13, 15, 16, 19, 21, 18])

# Mean of each experiment
mean_A = experiment_A.mean()
mean_B = experiment_B.mean()

# Standard deviation of each experiment
std_A = experiment_A.std()
std_B = experiment_B.std()

# Maximum value of each experiment
max_A = experiment_A.max()
max_B = experiment_B.max()

# Minimum value of each experiment
min_A = experiment_A.min()
min_B = experiment_B.min()

# Difference between the two experiments for each measurement
difference = experiment_A - experiment_B

# Display results
print(f"Mean       -> A: {mean_A:.2f}, B: {mean_B:.2f}")
print(f"Std Dev    -> A: {std_A:.2f}, B: {std_B:.2f}")
print(f"Max        -> A: {max_A}, B: {max_B}")
print(f"Min        -> A: {min_A}, B: {min_B}")
print(f"Difference (A - B): {difference}")

# Determine which experiment shows greater variation
if std_A > std_B:
    print(f"\nExperiment")

Mean       -> A: 16.00, B: 16.00
Std Dev    -> A: 2.45, B: 3.46
Max        -> A: 20, B: 21
Min        -> A: 12, B: 10
Difference (A - B): [ 2  2 -1  2  1 -4 -2]


In [18]:
def generate_dataset(rows=10, cols=5, low=0, high=100):
    return np.random.randint(low, high, size=(rows, cols))

def analyze_dataset(dataset):
    mean_per_variable = dataset.mean(axis=0)
    mean_per_experiment = dataset.mean(axis=1)
    overall_max = dataset.max()
    overall_min = dataset.min()
    overall_mean = dataset.mean()
    above_mean = dataset[dataset > overall_mean]
    return {
        'mean_per_variable': mean_per_variable,
        'mean_per_experiment': mean_per_experiment,
        'max': overall_max,
        'min': overall_min,
        'above_mean': above_mean
    }

dataset = generate_dataset()
print('Dataset:\n', dataset)
print('Shape:', dataset.shape, '| Dimensions:', dataset.ndim)

analysis = analyze_dataset(dataset)
for key, value in analysis.items():
    print(f'{key}: {value}')

reshaped = dataset.reshape(5, 10)
print('Reshaped (5x10):\n', reshaped)

flattened = reshaped.flatten()
print('Flattened back to 1D:', flattened)

Dataset:
 [[99 13 94 47 14]
 [71 77 86 61 39]
 [84 79 81 52 23]
 [25 88 59 40 28]
 [14 44 64 88 70]
 [ 8 87  0  7 87]
 [62 10 80  7 34]
 [34 32  4 40 27]
 [ 6 72 71 11 33]
 [32 47 22 61 87]]
Shape: (10, 5) | Dimensions: 2
mean_per_variable: [43.5 54.9 56.1 41.4 44.2]
mean_per_experiment: [53.4 66.8 63.8 48.  56.  37.8 38.6 27.4 38.6 49.8]
max: 99
min: 0
above_mean: [99 94 71 77 86 61 84 79 81 52 88 59 64 88 70 87 87 62 80 72 71 61 87]
Reshaped (5x10):
 [[99 13 94 47 14 71 77 86 61 39]
 [84 79 81 52 23 25 88 59 40 28]
 [14 44 64 88 70  8 87  0  7 87]
 [62 10 80  7 34 34 32  4 40 27]
 [ 6 72 71 11 33 32 47 22 61 87]]
Flattened back to 1D: [99 13 94 47 14 71 77 86 61 39 84 79 81 52 23 25 88 59 40 28 14 44 64 88
 70  8 87  0  7 87 62 10 80  7 34 34 32  4 40 27  6 72 71 11 33 32 47 22
 61 87]


In [19]:
def generate_marks(num_students=10, num_subjects=4):
    return np.random.randint(0, 101, size=(num_students, num_subjects))

def assign_grade(average):
    if average >= 90:
        return 'A'
    elif average >= 75:
        return 'B'
    elif average >= 60:
        return 'C'
    elif average >= 40:
        return 'D'
    else:
        return 'F'

def analyze_performance(marks):
    student_avg = marks.mean(axis=1)
    subject_avg = marks.mean(axis=0)
    best_student = student_avg.argmax()
    worst_student = student_avg.argmin()
    highest_mark = marks.max()
    lowest_mark = marks.min()
    count_above_75 = (student_avg > 75).sum()
    marks_above_90 = marks[marks > 90]
    return {
        'student_avg': student_avg,
        'subject_avg': subject_avg,
        'best_student': best_student,
        'worst_student': worst_student,
        'highest_mark': highest_mark,
        'lowest_mark': lowest_mark,
        'count_above_75': count_above_75,
        'marks_above_90': marks_above_90
    }

def build_student_records(marks, subjects):
    records = []
    for i, row in enumerate(marks):
        avg = row.mean()
        record = {
            'student': f'Student {i + 1}',
            'marks': dict(zip(subjects, row.tolist())),
            'average': round(float(avg), 2),
            'grade': assign_grade(avg)
        }
        records.append(record)
    return records

subjects = ['Math', 'Physics', 'Chemistry', 'Programming']
marks = generate_marks()
results = analyze_performance(marks)
records = build_student_records(marks, subjects)

print('Marks matrix:\n', marks)
print()
print('--- Analysis ---')
print('Average per student:', results['student_avg'])
print('Average per subject:', dict(zip(subjects, results['subject_avg'])))
print(f"Best student: Student {results['best_student'] + 1}")
print(f"Worst student: Student {results['worst_student'] + 1}")
print('Highest mark overall:', results['highest_mark'])
print('Lowest mark overall:', results['lowest_mark'])
print('Students with average > 75:', results['count_above_75'])
print('All marks > 90:', results['marks_above_90'])
print()
print('--- Student Report Card ---')
for record in records:
    print(f"{record['student']}: avg={record['average']}, grade={record['grade']}, marks={record['marks']}")

Marks matrix:
 [[ 36  98  43  85]
 [ 90  34  64  98]
 [100  46  77   2]
 [  0   4  89  13]
 [ 26   8  78  14]
 [ 89  41  76  50]
 [ 62  95  51  95]
 [  3  93 100  22]
 [ 14  42  28  35]
 [ 12  31  70  58]]

--- Analysis ---
Average per student: [65.5  71.5  56.25 26.5  31.5  64.   75.75 54.5  29.75 42.75]
Average per subject: {'Math': np.float64(43.2), 'Physics': np.float64(49.2), 'Chemistry': np.float64(67.6), 'Programming': np.float64(47.2)}
Best student: Student 7
Worst student: Student 4
Highest mark overall: 100
Lowest mark overall: 0
Students with average > 75: 1
All marks > 90: [ 98  98 100  95  95  93 100]

--- Student Report Card ---
Student 1: avg=65.5, grade=C, marks={'Math': 36, 'Physics': 98, 'Chemistry': 43, 'Programming': 85}
Student 2: avg=71.5, grade=C, marks={'Math': 90, 'Physics': 34, 'Chemistry': 64, 'Programming': 98}
Student 3: avg=56.25, grade=D, marks={'Math': 100, 'Physics': 46, 'Chemistry': 77, 'Programming': 2}
Student 4: avg=26.5, grade=F, marks={'Math': 0, 